/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:d7f016ab-2e2d-43b2-a184-308a043c48e2",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Vhd9CxycJ",
    "aws_user_pools_web_client_id": "3sbqnuoh4v3u9r213bjvmg2q6g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "sharetopiaimages172650-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
