name: run production action

on:
  push:
    branches: [ main ]

jobs:
  test:
    # runs all tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install all packages
      working-directory: ./sharetopia-frontend
      run: npm ci
    - name: Run unit tests
      working-directory: ./sharetopia-frontend
      run: npm run test:unit

  deploy: 
    # runs all tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install all packages
        working-directory: ./sharetopia-frontend
        run: npm ci
  
      - name: Run build
        working-directory: ./sharetopia-frontend
        run: npm run build
        
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=./sharetopia-frontend/dist --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
  
