name: Test and deploy staging version to surge

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install all packages
        working-directory: ./sharetopia-frontend
        run: npm ci
      - name: Run unit tests
        working-directory: ./sharetopia-frontend
        run: npm run test:unit

  build_and_deploy:
    runs-on: ubuntu-latest
    name: build and deploy (staging)
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install all packages
        working-directory: ./sharetopia-frontend
        run: npm ci
      - name: Run build
        working-directory: ./sharetopia-frontend
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: save build to dist
          path: ./sharetopia-frontend/dist
      # deploy to surge
      - run: npm install -g surge
      - uses: nelonoel/branch-name@v1
      - run: surge ./sharetopia-frontend/dist ${{ BRANCH_NAME }}${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
