name: Test and deploy staging version to surge

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install all packages
        working-directory: ./sharetopia-frontend
        run: npm ci
      - name: Run unit tests
        working-directory: ./sharetopia-frontend
        run: npm run test:unit

  build:
    runs-on: ubuntu-latest
    name: Building for production
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install all packages
        working-directory: ./sharetopia-frontend
        run: npm ci
      - name: Run build
        working-directory: ./sharetopia-frontend
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: save build to dist
          path: ./sharetopia-frontend/dist

  deploy:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: npm install -g surge
      - run: surge ./sharetopia-frontend/dist ${{ steps.extract_branch.outputs.branch }}-${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
